// <auto-generated />
using System;
using IOT.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOT.Persistence.Migrations
{
    [DbContext(typeof(IOTDbContext))]
    [Migration("20240318071016_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IOT.Domain.Detail", b =>
                {
                    b.Property<string>("DetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetailStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DetailId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Detail");
                });

            modelBuilder.Entity("IOT.Domain.DetailPicture", b =>
                {
                    b.Property<Guid>("DetailPictureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("DetailPictureId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("DetailPicture");
                });

            modelBuilder.Entity("IOT.Domain.Machine", b =>
                {
                    b.Property<string>("MachineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MachineId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("IOT.Domain.Oder", b =>
                {
                    b.Property<string>("OderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OderId");

                    b.ToTable("Oder");
                });

            modelBuilder.Entity("IOT.Domain.OEE", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("IdleTime")
                        .HasColumnType("real");

                    b.Property<float>("Oee")
                        .HasColumnType("real");

                    b.Property<float>("OperationTime")
                        .HasColumnType("real");

                    b.Property<float>("ShiftTime")
                        .HasColumnType("real");

                    b.HasKey("TimeStamp", "MachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("OEE");
                });

            modelBuilder.Entity("IOT.Domain.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RealEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("OderId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("IOT.Domain.Worker", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("IOT.Domain.WorkerPicture", b =>
                {
                    b.Property<Guid>("WorkerPictureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("WorkerPictureId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerPicture");
                });

            modelBuilder.Entity("IOT.Domain.Detail", b =>
                {
                    b.HasOne("IOT.Domain.Machine", "Machine")
                        .WithMany("Details")
                        .HasForeignKey("MachineId");

                    b.HasOne("IOT.Domain.Project", "Project")
                        .WithMany("Details")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IOT.Domain.Worker", "Worker")
                        .WithMany("Details")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Machine");

                    b.Navigation("Project");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("IOT.Domain.DetailPicture", b =>
                {
                    b.HasOne("IOT.Domain.Detail", "Detail")
                        .WithMany("DetailPictures")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("IOT.Domain.OEE", b =>
                {
                    b.HasOne("IOT.Domain.Machine", "machine")
                        .WithMany("OEEs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("machine");
                });

            modelBuilder.Entity("IOT.Domain.Project", b =>
                {
                    b.HasOne("IOT.Domain.Oder", "Oder")
                        .WithMany("Projects")
                        .HasForeignKey("OderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oder");
                });

            modelBuilder.Entity("IOT.Domain.WorkerPicture", b =>
                {
                    b.HasOne("IOT.Domain.Worker", "Worker")
                        .WithMany("WorkerPictures")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("IOT.Domain.Detail", b =>
                {
                    b.Navigation("DetailPictures");
                });

            modelBuilder.Entity("IOT.Domain.Machine", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("OEEs");
                });

            modelBuilder.Entity("IOT.Domain.Oder", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("IOT.Domain.Project", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("IOT.Domain.Worker", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("WorkerPictures");
                });
#pragma warning restore 612, 618
        }
    }
}
